apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitorings.monitoring.massive.dynamic.io
spec:
  group: monitoring.massive.dynamic.io
  names:
    kind: Monitoring
    listKind: MonitoringList
    plural: monitorings
    singular: monitoring
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
