apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scans.scan.massive.dynamic.io
spec:
  group: scan.massive.dynamic.io
  names:
    kind: Scan
    listKind: ScanList
    plural: scans
    singular: scan
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
