apiVersion: apps/v1
kind: Deployment
metadata:
  name: massive-dynamic-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: massive-dynamic-operator
  template:
    metadata:
      labels:
        name: massive-dynamic-operator
    spec:
      serviceAccountName: massive-dynamic-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "hrvoje6/massive-dynamic-operator:v1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "hrvoje6/massive-dynamic-operator:v1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "massive-dynamic-operator"
      volumes:
        - name: runner
          emptyDir: {}
