---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  clusterIP: None
  selector:
    component: elasticsearch
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: node-to-node
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: monitoring
data:
  elasticsearch.yml: |-
    cluster.name: massive-dynamic-monitoring
    network.host: 0.0.0.0

    discovery.type: single-node

    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: false
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox:1.27.2
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      - name: file-permissions
        image: busybox:1.27.2
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/data']
        volumeMounts:
        - name: data-es
          mountPath: /usr/share/elasticsearch/data
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config-volume-elasticsearch
          subPath: elasticsearch.yml
        - name: data-es
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: config-volume-elasticsearch
        configMap:
          name: elasticsearch-config
      - name: data-es
        hostPath:
          path: /var/lib/elasticsearch-data
          type: DirectoryOrCreate